# -*- coding: utf-8 -*-
"""CEPython.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1K3Fn7faLWZs5soRSkQ2npwTpR0YmdoYc
"""

import requests

def lala():
  print('CEPython')

  cep = input('Digite o CEP para consulta: ')

  while len(cep) != 8 :
    print('Quantidade de dígitos inválida')
    cep = input('Digite o CEP para a consulta: ')

  caixinha = requests.get('https://viacep.com.br/ws/{}/json/'.format(cep))
  endereco = caixinha.json()
  if 'erro' not in endereco:
    print('~~> CEP ENCONTRADO <~~')
    print("CEP: " + endereco['cep'])
    print('Cidade: {}'.format(endereco['localidade']))
    print(f"Estado: {endereco['uf']}")
    print("Logradouro: " + endereco ['logradouro'])
  else:
    print('{}: CEP inválido.'.format(cep))

  print('------------------------------------------------------') 

  def validacao():
    opcao = input('Deseja realizar outra consulta? \n 1. Sim \n 2. Sair \n ')
    if opcao == "1" or opcao == "2":
      if int(opcao) == 1:
        lala()
      else:
        print('Até mais!!!')
    else:
      print("Opção inválida")
      validacao()
  validacao()    
lala()